In [59]:
import pandas as pd
import numpy as np

In [60]:
df = pd.read_csv("./checking2.csv", thousands=",", encoding="CP949")
df.drop(columns=["Unnamed: 0", "count"], inplace=True)

In [61]:
df['부실기업'] = df['부실기업'].fillna(0)

In [62]:
df

            회사명  거래소코드    회계년도  이자보상배율  부실기업
0      (주)CMG제약  58820  11-Dec    3.53   0.0
1      (주)CMG제약  58820  12-Dec   -7.75   0.0
2      (주)CMG제약  58820  13-Dec    0.70   1.0
3      (주)CMG제약  58820  14-Dec    3.60   0.0
4      (주)CMG제약  58820  15-Dec  -32.22   0.0
...         ...    ...     ...     ...   ...
15145   흥아해운(주)   3280  15-Dec    1.02   0.0
15146   흥아해운(주)   3280  16-Dec    0.21   0.0
15147   흥아해운(주)   3280  17-Dec   -0.42   1.0
15148   흥아해운(주)   3280  18-Dec   -1.16   1.0
15149   흥아해운(주)   3280  19-Dec   -0.55   1.0

[15150 rows x 5 columns]

In [68]:
df['이보배2'] = df['이자보상배율'].shift(-1).where(df['회사명']==(df['회사명']).shift(-1))
df

            회사명  거래소코드    회계년도  이자보상배율  부실기업   이보배2
0      (주)CMG제약  58820  11-Dec    3.53   0.0  -7.75
1      (주)CMG제약  58820  12-Dec   -7.75   0.0   0.70
2      (주)CMG제약  58820  13-Dec    0.70   1.0   3.60
3      (주)CMG제약  58820  14-Dec    3.60   0.0 -32.22
4      (주)CMG제약  58820  15-Dec  -32.22   0.0   0.00
...         ...    ...     ...     ...   ...    ...
15145   흥아해운(주)   3280  15-Dec    1.02   0.0   0.21
15146   흥아해운(주)   3280  16-Dec    0.21   0.0  -0.42
15147   흥아해운(주)   3280  17-Dec   -0.42   1.0  -1.16
15148   흥아해운(주)   3280  18-Dec   -1.16   1.0  -0.55
15149   흥아해운(주)   3280  19-Dec   -0.55   1.0    NaN

[15150 rows x 6 columns]

In [70]:
df.head(30)

         회사명  거래소코드    회계년도  이자보상배율  부실기업    이보배2
0   (주)CMG제약  58820  11-Dec    3.53   0.0   -7.75
1   (주)CMG제약  58820  12-Dec   -7.75   0.0    0.70
2   (주)CMG제약  58820  13-Dec    0.70   1.0    3.60
3   (주)CMG제약  58820  14-Dec    3.60   0.0  -32.22
4   (주)CMG제약  58820  15-Dec  -32.22   0.0    0.00
5   (주)CMG제약  58820  16-Dec    0.00   0.0    0.00
6   (주)CMG제약  58820  17-Dec    0.00   0.0    0.00
7   (주)CMG제약  58820  18-Dec    0.00   0.0  303.00
8   (주)CMG제약  58820  19-Dec  303.00   0.0     NaN
9   (주)DB하이텍    990  11-Dec   -0.75   0.0   -0.31
10  (주)DB하이텍    990  12-Dec   -0.31   1.0   -0.16
11  (주)DB하이텍    990  13-Dec   -0.16   1.0    0.67
12  (주)DB하이텍    990  14-Dec    0.67   1.0    2.50
13  (주)DB하이텍    990  15-Dec    2.50   0.0    4.41
14  (주)DB하이텍    990  16-Dec    4.41   0.0    6.05
15  (주)DB하이텍    990  17-Dec    6.05   0.0    6.77
16  (주)DB하이텍    990  18-Dec    6.77   0.0   13.44
17  (주)DB하이텍    990  19-Dec   13.44   0.0     NaN
18   (주)ES큐브  50120  11-Dec -245.99   0.0    1.72
19   (주)ES큐브  50120  12-Dec    1.72   0.0  -37.44
20   (주)ES큐브  50120  13-Dec  -37.44   0.0   22.20
21   (주)ES큐브  50120  14-Dec   22.20   0.0  -11.86
22   (주)ES큐브  50120  15-Dec  -11.86   0.0    8.98
23   (주)ES큐브  50120  16-Dec    8.98   0.0    2.86
24   (주)ES큐브  50120  17-Dec    2.86   0.0   -0.82
25   (주)ES큐브  50120  18-Dec   -0.82   0.0   -0.68
26   (주)ES큐브  50120  19-Dec   -0.68   1.0     NaN
27  (주)HJ중공업  97230  11-Dec    0.55   0.0    0.27
28  (주)HJ중공업  97230  12-Dec    0.27   1.0   -0.40
29  (주)HJ중공업  97230  13-Dec   -0.40   1.0   -0.88

In [71]:
df2 = df[['회사명', '거래소코드', '회계년도', '이자보상배율', '이보배2', '부실기업']]
df2

            회사명  거래소코드    회계년도  이자보상배율   이보배2  부실기업
0      (주)CMG제약  58820  11-Dec    3.53  -7.75   0.0
1      (주)CMG제약  58820  12-Dec   -7.75   0.70   0.0
2      (주)CMG제약  58820  13-Dec    0.70   3.60   1.0
3      (주)CMG제약  58820  14-Dec    3.60 -32.22   0.0
4      (주)CMG제약  58820  15-Dec  -32.22   0.00   0.0
...         ...    ...     ...     ...    ...   ...
15145   흥아해운(주)   3280  15-Dec    1.02   0.21   0.0
15146   흥아해운(주)   3280  16-Dec    0.21  -0.42   0.0
15147   흥아해운(주)   3280  17-Dec   -0.42  -1.16   1.0
15148   흥아해운(주)   3280  18-Dec   -1.16  -0.55   1.0
15149   흥아해운(주)   3280  19-Dec   -0.55    NaN   1.0

[15150 rows x 6 columns]

In [72]:
df2.head(15)

         회사명  거래소코드    회계년도  이자보상배율    이보배2  부실기업
0   (주)CMG제약  58820  11-Dec    3.53   -7.75   0.0
1   (주)CMG제약  58820  12-Dec   -7.75    0.70   0.0
2   (주)CMG제약  58820  13-Dec    0.70    3.60   1.0
3   (주)CMG제약  58820  14-Dec    3.60  -32.22   0.0
4   (주)CMG제약  58820  15-Dec  -32.22    0.00   0.0
5   (주)CMG제약  58820  16-Dec    0.00    0.00   0.0
6   (주)CMG제약  58820  17-Dec    0.00    0.00   0.0
7   (주)CMG제약  58820  18-Dec    0.00  303.00   0.0
8   (주)CMG제약  58820  19-Dec  303.00     NaN   0.0
9   (주)DB하이텍    990  11-Dec   -0.75   -0.31   0.0
10  (주)DB하이텍    990  12-Dec   -0.31   -0.16   1.0
11  (주)DB하이텍    990  13-Dec   -0.16    0.67   1.0
12  (주)DB하이텍    990  14-Dec    0.67    2.50   1.0
13  (주)DB하이텍    990  15-Dec    2.50    4.41   0.0
14  (주)DB하이텍    990  16-Dec    4.41    6.05   0.0

In [74]:
for i in range(0, len(df2)):
    if df2.iloc[i]['이자보상배율'] < 1 and df2.iloc[i]['이보배2'] > 1:
        df2.loc[i, '회생여부'] = 1

C:\Users\luck1\AppData\Local\Temp\ipykernel_12064\2037182408.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.loc[i, '회생여부'] = 1

In [76]:
df2.to_csv("checking4.csv", encoding="CP949")

In [83]:
(df2['회생여부']==df2['부실기업']).value_counts()

False    14631
True       519
dtype: int64

In [67]:
# count = 0
# company = df.loc[0, '회사명']

# for i in range(0, len(df)):

#     # 회사명 다르면
#     if company != df.iloc[i]['회사명']:
#         # 회사명 기록하고
#         company = df.iloc[i]['회사명']
#         # 카운트 초기화하고
#         count = 0

#     if df.iloc[i]['부실기업'] == 1:
#         count += 1

#     if count > 0 and df.iloc[i]['부실기업'] == 0:
#         df.loc[i, "survived"] = 1