In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
# 경고가 많아지면 곤란해서 추가
import warnings
warnings.filterwarnings('ignore')

In [3]:
# csv 파일 리스트 가져오기
files = os.listdir("../csv_data/use/")
path = "../csv_data/use/"

#files

In [4]:
# df_a = pd.concat([df_a, df_b.iloc[:,-2:]], axis=1)
# df_a

In [5]:
# concat의 기초가 되어줄 데이터프레임
# 이자보상배율

df_a = pd.read_csv("../raw_data/전체데이터_2011_코스피코스닥_v1.3.csv", thousands=',', encoding="CP949").reset_index(drop=True)
df_a

,회사명,거래소코드,회계년도,이자보상배율(이자비용)(IFRS),이자보상배율(이자비용)(IFRS연결),Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,(주)CMG제약,58820,11-Dec,3.94,3.53,NaN,NaN,NaN,NaN
1,(주)CMG제약,58820,12-Dec,-7.45,-7.75,NaN,NaN,NaN,NaN
2,(주)CMG제약,58820,13-Dec,0.73,0.7,NaN,NaN,NaN,NaN
3,(주)CMG제약,58820,14-Dec,3.63,3.6,NaN,NaN,NaN,NaN
4,(주)CMG제약,58820,15-Dec,-32.2,-32.22,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
15145,흥아해운(주),3280,15-Dec,0.79,1.02,NaN,NaN,NaN,NaN
15146,흥아해운(주),3280,16-Dec,0.04,0.21,NaN,NaN,NaN,NaN
15147,흥아해운(주),3280,17-Dec,-0.61,-0.42,NaN,NaN,NaN,NaN
15148,흥아해운(주),3280,18-Dec,-1.26,-1.16,NaN,NaN,NaN,NaN
15149,흥아해운(주),3280,19-Dec,-0.58,-0.55,NaN,NaN,NaN,NaN

In [6]:
# csv 하나 하나 불러오면서 저 옆에 붙입니다

for file in files:
    df_b = pd.read_csv(path+file, thousands=",", encoding="CP949")
    df_b.drop(columns=["Unnamed: 0"], inplace=True)

    df_a = pd.concat([df_a, df_b.iloc[:,-2:]], axis=1)

In [9]:
df_temp = pd.read_csv("../csv_data/01_활동성확인용.csv", thousands=",", encoding="CP949")
df_temp.iloc[:,-16:]

,총자본회전율(개별),총자본회전율(연결),재고자산회전율(개별),재고자산회전율(연결),매출채권회전율(개별),매출채권회전율(연결),유형자산회전율(개별),유형자산회전율(연결)),매입채무회전율(개별),매입채무회전율(연결),자기자본회전율(개별),자기자본회전율(연결),타인자본회전율(개별),타인자본회전율(연결),유동자산회전율(개별),유동자산회전율(연결)
0,0.967500,0.974315,3.737263,3.737263,1.901091,1.901091,1.777885,1.772988,11.953510,11.953510,0.967500,0.974315,2.014020,2.012498,1.254267,1.250896
1,0.651604,0.655130,4.088497,4.088497,1.450546,1.450546,1.718625,1.709722,7.829457,7.829457,0.651604,0.655130,0.938433,0.934532,0.521521,0.520586
2,0.503954,0.506332,3.302614,3.302614,1.602567,1.608876,2.025203,2.028795,6.174374,6.198680,0.503954,0.506332,1.258357,1.258124,0.476306,0.478256
3,0.463793,0.464339,3.004263,3.004263,1.478089,1.478089,1.535321,1.535321,5.272077,5.272077,0.463793,0.464339,2.848797,2.847461,0.683069,0.684179
4,0.563727,0.564493,3.324965,3.324965,1.657734,1.657734,1.475432,1.475432,5.655170,5.655170,0.563727,0.564493,2.879964,2.878081,0.988905,0.991044
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14902,5.077020,4.964267,61.879371,64.233139,25.850880,24.382231,2.004289,2.094676,15.739421,16.050269,5.077020,4.964267,1.479909,1.536013,5.946233,5.833991
14903,4.513130,4.550483,51.397358,53.935716,25.793855,24.299406,1.359188,1.441049,15.875451,16.257836,4.513130,4.550483,1.140216,1.201416,7.240475,6.978201
14904,5.358582,5.407265,41.010767,43.166320,22.934774,22.183634,1.274368,1.358548,14.895284,15.392707,5.358582,5.407265,1.051492,1.116637,7.935881,7.681440
14905,8.579521,7.934063,37.374860,39.235457,18.218762,18.168919,1.345698,1.431814,11.159149,11.869002,8.579521,7.934063,0.970718,1.030840,6.746457,6.730041
14906,2.618934,1.963471,7.498556,7.276902,4.546242,4.312897,0.267504,0.279288,2.258365,2.407800,2.618934,1.963471,0.177862,0.180731,1.184891,1.010727

In [173]:
# 개별재무제표와 연결재무제표 중 비교해서 집어넣는 작업을 위한 전처리

df = pd.DataFrame(columns= ["회사명", "거래소코드", "회계년도", '이자보상배율', 'cashflow_매출액비율', 'cashflow_부채비율',
       '당좌비율', '매입채무회전율', '매출액순이익률', '매출액총이익률', '매출액영업이익률', '매출액증가율',
       '매출원가대매출액비율', '매출채권회전율', '부채비율', '순이익증가율', '영업이익증가율', '유동부채', '유동비율',
       '유동자산구성비율', '유동자산증가율', '유형자산증가율', '유형자산회전율', '자기자본구성비율', '자본증가율',
       '타인자본회전율', '재고자산_유동자산비율', '재고자산증가율', '재고자산회전율',
       '차입금의존도', '차입금평균이자율', '총자본영업이익률', '총자산순이익률',
       '총자산증가율', '총자산회전율', '현금비율'])

df["회사명"] = df_a["회사명"]
df["거래소코드"] = df_a["거래소코드"]
df["회계년도"] = pd.to_datetime(df_a['회계년도'].str.upper(), format="%d-%b", yearfirst=False).dt.strftime("20%d")
df

,회사명,거래소코드,회계년도,이자보상배율,cashflow_매출액비율,cashflow_부채비율,당좌비율,매입채무회전율,매출액순이익률,매출액총이익률,...,재고자산_유동자산비율,재고자산증가율,재고자산회전율,차입금의존도,차입금평균이자율,총자본영업이익률,총자산순이익률,총자산증가율,총자산회전율,현금비율
0,(주)CMG제약,58820,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,(주)CMG제약,58820,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,(주)CMG제약,58820,2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,(주)CMG제약,58820,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,(주)CMG제약,58820,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15145,흥아해운(주),3280,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15146,흥아해운(주),3280,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15147,흥아해운(주),3280,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15148,흥아해운(주),3280,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15149,흥아해운(주),3280,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [174]:
len(df_a)

15150

In [175]:
# csv 한바퀴 돌립니다

df_ind = pd.DataFrame(columns= ["회사명", "거래소코드", "회계년도"])
df_oth = df_ind

for i in range(3, len(df_a.columns)-1, 2):

    # 개별재무제표 저장
    df_x = pd.DataFrame(df_a.iloc[:, i])
    df_ind = pd.concat([df_ind, df_x], axis=1)

for i in range(4, len(df_a.columns), 2):

    # 연결재무제표 저장
    df_y = pd.DataFrame(df_a.iloc[:, i])
    df_oth = pd.concat([df_oth, df_y], axis=1)

In [178]:
print(len(df.columns))
print(len(df_ind.columns))
print(len(df_oth.columns))

36
36
36

In [183]:
for i in range(3, len(df)):
    # 컬럼들 순회합니다
    for j in range(3, len(df.columns)):
        # df_ind 에 결측치가 없다면
        if not pd.isna(df_ind.iloc[i][j]):
            # df_oth 에도 결측치가 없다면
            if not pd.isna(df_oth.iloc[i][j]):
                # df_oth 삽입
                df.iloc[i, j] = df_oth.iloc[i][j]

            # df_oth 가 결측치라면
            else:
                #df_ind 값 삽입
                df.iloc[i, j] = df_ind.iloc[i][j]

        # df_ind 에 결측치가 있다면
        else:
            # df_oth 에 결측치가 없다면
            if not pd.isna(df_oth.iloc[i][j]):
                # df_oth 삽입
                df.iloc[i, j] = df_oth.iloc[i][j]

            # 둘 다 결측치면 일단 패스
            else:
                pass

In [185]:
df.to_csv("../csv_data/00_합체완료.csv", encoding="CP949")

In [186]:
df.head(3)

,회사명,거래소코드,회계년도,이자보상배율,cashflow_매출액비율,cashflow_부채비율,당좌비율,매입채무회전율,매출액순이익률,매출액총이익률,...,재고자산_유동자산비율,재고자산증가율,재고자산회전율,차입금의존도,차입금평균이자율,총자본영업이익률,총자산순이익률,총자산증가율,총자산회전율,현금비율
0,(주)CMG제약,58820,2011,3.53,-24.066146,-46.081054,165.032796,11.982404,-8.496548,41.832069,...,17.970021,0.0,6.471395,1.750645,0.0,1.729531,-5.523791,0.891189,0.650122,15.097437
1,(주)CMG제약,58820,2012,-7.75,-12.712766,-8.098449,649.984153,6.086141,-40.971945,28.339519,...,6.27779,0.0,5.500657,30.577772,0.0,-6.656239,-11.662368,-0.209132,0.284643,68.810446
2,(주)CMG제약,58820,2013,0.7,-13.507392,-39.850832,610.736781,5.21547,1.451715,38.698504,...,12.072281,0.0,4.417273,2.531106,0.0,0.807443,0.529722,0.087739,0.364894,394.634328

In [187]:
# 현재 데이터 기준으로 2년 연속 이.보.배 1 미만인 기업을 찾을 겁니다

f_company = [] # 2년 연속 이.보.배 1 미만 기업을 저장하는 리스트
f_year = [] # 2년째 최초 연도
count = 0 # 한계기업 카운트용
company = 'x' # 한계기업 기록용

# 이거도 csv 한바퀴 돌립니다
for i in range(0, len(df)):

    # 회사명이 이미 기록된 상태에서 또 중복으로 적을 필요는 없습니다
    if company == df.iloc[i]['회사명']:
        continue

    # 이자보상배율이 1 미만인 경우 카운트를 늘립니다
    if df.iloc[i]['이자보상배율'] < 1:
            count += 1
    # 도중에 이자보상배율이 1 미만이면 탈출합니다
    else:
        count = 0

    # 한계 기업 클럽에 오셨습니다. 환영합니다.
    if count == 2:
        company = df.iloc[i]['회사명']
        f_company.append(company)
        f_year.append(df.iloc[i]['회계년도'])
        count = 0

In [189]:
limit_c = df.isin(f_company)
limit_c

,회사명,거래소코드,회계년도,이자보상배율,cashflow_매출액비율,cashflow_부채비율,당좌비율,매입채무회전율,매출액순이익률,매출액총이익률,...,재고자산_유동자산비율,재고자산증가율,재고자산회전율,차입금의존도,차입금평균이자율,총자본영업이익률,총자산순이익률,총자산증가율,총자산회전율,현금비율
0,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15145,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
15146,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
15147,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
15148,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
15149,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [191]:
df_temp = [] # 임시 저장용 리스트

# 그렇게 만든 데이터프레임을 기존과 비교해서 True인 애들만 뽑아옵니다
for i in range(0, len(limit_c)-1):
    if limit_c.iloc[i]["회사명"] == True:
        df_temp.append(df.loc[i])

# 그리고 저장을 합니다
limit_company = pd.DataFrame(df_temp).reset_index(drop=True)
limit_company.to_csv("../csv_data/00_한계기업v1_0.csv", encoding="CP949")