In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../csv_data/00_이자보상배율.csv", encoding="CP949")
df.drop(columns=['Unnamed: 0'], inplace=True)

In [3]:
df['회계년도'] = pd.to_datetime(df['회계년도'].str.upper(), format="%d-%b", yearfirst=False).dt.strftime("20%d")
df

            회사명  거래소코드  회계년도  이자보상배율
0      (주)CMG제약  58820  2011    3.53
1      (주)CMG제약  58820  2012   -7.75
2      (주)CMG제약  58820  2013    0.70
3      (주)CMG제약  58820  2014    3.60
4      (주)CMG제약  58820  2015  -32.22
...         ...    ...   ...     ...
15145   흥아해운(주)   3280  2015    1.02
15146   흥아해운(주)   3280  2016    0.21
15147   흥아해운(주)   3280  2017   -0.42
15148   흥아해운(주)   3280  2018   -1.16
15149   흥아해운(주)   3280  2019    0.00

[15150 rows x 4 columns]

In [4]:
df2 = df.sort_values('회계년도')
df2

              회사명   거래소코드  회계년도   이자보상배율
0        (주)CMG제약   58820  2011     3.53
5994   (주)이엔코퍼레이션   66980  2011    -2.42
6003     (주)이엔플러스   74610  2011    -5.61
6015       (주)이엠넷  123570  2011    91.47
6024     (주)이엠앤아이   83470  2011     0.11
...           ...     ...   ...      ...
13319   제이씨케미칼(주)  137950  2019     4.63
6103     (주)이크레더블   92130  2019  1894.52
6112       (주)이퓨쳐  134060  2019    35.81
13310  제이스코홀딩스(주)   23440  2019    -7.33
15149     흥아해운(주)    3280  2019     0.00

[15150 rows x 4 columns]

In [5]:
c = -10
d = -5

if c < 0 and d < 0 : print(c/d*-1)
else: print(c/d)

-2.0

In [6]:
df_test = pd.read_csv("../csv_data/00_매출감소율.csv", encoding="CP949")
df_test

,Unnamed: 0,회사명,거래소코드,회계년도,이자보상배율,매출액(수익)(*)(IFRS)(천원),매출원가(*)(IFRS)(천원),매출액(수익)(*)(IFRS연결)(천원),매출원가(*)(IFRS연결)(천원),통계청 한국표준산업분류 10차(중분류),매출액(수익)감소,매출원가감소,매출액(수익)감소(연결),매출원가감소(연결)
0,0,(주)CMG제약,58820,2011,3.53,17751704.0,10325799.0,17751704.0,10325799.0,의료용 물질 및 의약품 제조업,NaN,NaN,NaN,NaN
1,1,(주)CMG제약,58820,2012,-7.75,16255389.0,11648690.0,16255389.0,11648690.0,의료용 물질 및 의약품 제조업,0.092050,-0.113566,0.092050,-0.113566
2,2,(주)CMG제약,58820,2013,0.70,20322140.0,12506817.0,20402140.0,12506817.0,의료용 물질 및 의약품 제조업,-0.200114,-0.068613,-0.203251,-0.068613
3,3,(주)CMG제약,58820,2014,3.60,22752584.0,14318048.0,22752584.0,14318048.0,의료용 물질 및 의약품 제조업,-0.106821,-0.126500,-0.103304,-0.126500
4,4,(주)CMG제약,58820,2015,-32.22,27041894.0,17237814.0,27041894.0,17237814.0,의료용 물질 및 의약품 제조업,-0.158617,-0.169381,-0.158617,-0.169381
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15145,15145,흥아해운(주),3280,2015,1.02,801560945.0,763642673.0,845115359.0,792690121.0,수상 운송업,-0.015357,-0.012346,-0.023630,-0.017475
15146,15146,흥아해운(주),3280,2016,0.21,779990350.0,756984914.0,831746081.0,794370084.0,수상 운송업,0.027655,0.008795,0.016074,-0.002115
15147,15147,흥아해운(주),3280,2017,-0.42,780863972.0,778062692.0,836427496.0,818958179.0,수상 운송업,-0.001119,-0.027090,-0.005597,-0.030024
15148,15148,흥아해운(주),3280,2018,-1.16,705007198.0,724528226.0,753865569.0,760867431.0,수상 운송업,0.107597,0.073889,0.109518,0.076348
15149,15149,흥아해운(주),3280,2019,0.00,97376909.0,98752599.0,102166838.0,96504366.0,수상 운송업,6.239983,6.336802,6.378770,6.884280

In [7]:
df_test.columns

Index(['Unnamed: 0', '회사명', '거래소코드', '회계년도', '이자보상배율', '매출액(수익)(*)(IFRS)(천원)',
       '매출원가(*)(IFRS)(천원)', '매출액(수익)(*)(IFRS연결)(천원)', '매출원가(*)(IFRS연결)(천원)',
       '통계청 한국표준산업분류 10차(중분류)', '매출액(수익)감소', '매출원가감소', '매출액(수익)감소(연결)',
       '매출원가감소(연결)'],
      dtype='object')

In [8]:
# 위에 있는 columns로 필요한 컬럼 확인하고 복붙하세요
df_test = df_test[['매출액(수익)감소', '매출원가감소', '매출액(수익)감소(연결)','매출원가감소(연결)']]
df_test

       매출액(수익)감소    매출원가감소  매출액(수익)감소(연결)  매출원가감소(연결)
0            NaN       NaN            NaN         NaN
1       0.092050 -0.113566       0.092050   -0.113566
2      -0.200114 -0.068613      -0.203251   -0.068613
3      -0.106821 -0.126500      -0.103304   -0.126500
4      -0.158617 -0.169381      -0.158617   -0.169381
...          ...       ...            ...         ...
15145  -0.015357 -0.012346      -0.023630   -0.017475
15146   0.027655  0.008795       0.016074   -0.002115
15147  -0.001119 -0.027090      -0.005597   -0.030024
15148   0.107597  0.073889       0.109518    0.076348
15149   6.239983  6.336802       6.378770    6.884280

[15150 rows x 4 columns]

In [9]:
for i in range(0, len(df_test)):
    if df_test.iloc[i]['매출액(수익)감소'] < 0 and df_test.iloc[i]['매출원가감소'] < 0 :
        df_test.loc[i, '예시1'] = df_test.iloc[i]['매출액(수익)감소'] / df_test.iloc[i]['매출원가감소'] * -1
    # elif df_test.iloc[i]['매출원가감소'] == 0:
    #     df_test.loc[i, '예시1'] = 0
    else:
        df_test.loc[i, '예시1'] = df_test.iloc[i]['매출액(수익)감소'] / df_test.iloc[i]['매출원가감소']

C:\Users\luck1\AppData\Local\Temp\ipykernel_2448\2630210314.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test.loc[i, '예시1'] = df_test.iloc[i]['매출액(수익)감소'] / df_test.iloc[i]['매출원가감소']
C:\Users\luck1\AppData\Local\Temp\ipykernel_2448\2630210314.py:7: RuntimeWarning: divide by zero encountered in double_scalars
  df_test.loc[i, '예시1'] = df_test.iloc[i]['매출액(수익)감소'] / df_test.iloc[i]['매출원가감소']
C:\Users\luck1\AppData\Local\Temp\ipykernel_2448\2630210314.py:7: RuntimeWarning: invalid value encountered in double_scalars
  df_test.loc[i, '예시1'] = df_test.iloc[i]['매출액(수익)감소'] / df_test.iloc[i]['매출원가감소']

In [10]:
df_test

       매출액(수익)감소    매출원가감소  매출액(수익)감소(연결)  매출원가감소(연결)       예시1
0            NaN       NaN            NaN         NaN       NaN
1       0.092050 -0.113566       0.092050   -0.113566 -0.810548
2      -0.200114 -0.068613      -0.203251   -0.068613 -2.916576
3      -0.106821 -0.126500      -0.103304   -0.126500 -0.844432
4      -0.158617 -0.169381      -0.158617   -0.169381 -0.936450
...          ...       ...            ...         ...       ...
15145  -0.015357 -0.012346      -0.023630   -0.017475 -1.243880
15146   0.027655  0.008795       0.016074   -0.002115  3.144358
15147  -0.001119 -0.027090      -0.005597   -0.030024 -0.041299
15148   0.107597  0.073889       0.109518    0.076348  1.456205
15149   6.239983  6.336802       6.378770    6.884280  0.984721

[15150 rows x 5 columns]

In [11]:
# 자기자본순이익률 = 당기/자기자본 * 100

df_rate_a = pd.read_csv("../raw_data/자기자본순이익률_raw.csv", encoding="CP949")

FileNotFoundError: [Errno 2] No such file or directory: '../raw_data/자기자본순이익률_raw.csv'

In [12]:
df_rate_a

NameError: name 'df_rate_a' is not defined

In [ ]:
#AC_con['prev_자산'] = AC_con['자산'].shift().where(AC_con.회사명.eq(AC_con.회사명.shift()))

df_rate_a["[제조]자본(*)(IFRS연결2)"] = df_rate_a["[제조]자본(*)(IFRS연결)"].shift().where(df_rate_a.회사명.eq(df_rate_a.회사명.shift()))
df_rate_a["[제조]자본(*)(IFRS2)"] = df_rate_a["[제조]자본(*)(IFRS)"].shift().where(df_rate_a.회사명.eq(df_rate_a.회사명.shift()))
df_rate_a.head(15)

,회사명,거래소코드,회계년도,[제조]자본(*)(IFRS연결),[제조]당기순이익(손실)(IFRS연결),[제조]자본(*)(IFRS),[제조]당기순이익(손실)(IFRS),[제조]자본(*)(IFRS연결2),[제조]자본(*)(IFRS2)
0,(주)CMG제약,58820,2010/12,18405116.0,-6945220.0,18405116.0,-6945220.0,NaN,NaN
1,(주)CMG제약,58820,2011/12,18034249.0,-1508282.0,18290915.0,-1264488.0,18405116.0,18405116.0
2,(주)CMG제약,58820,2012/12,31590685.0,-6660149.0,31602540.0,-6892739.0,18034249.0,18290915.0
3,(주)CMG제약,58820,2013/12,48997281.0,296181.0,49048213.0,335258.0,31590685.0,31602540.0
4,(주)CMG제약,58820,2014/12,49002644.0,158039.0,49067039.0,171502.0,48997281.0,49048213.0
...,...,...,...,...,...,...,...,...,...
16498,흥아해운(주),3280,2015/12,173076634.0,10517216.0,161824549.0,8827312.0,167402807.0,153935831.0
16499,흥아해운(주),3280,2016/12,192487245.0,-17173253.0,183829287.0,-16149442.0,173076634.0,161824549.0
16500,흥아해운(주),3280,2017/12,116884496.0,-73500411.0,107614965.0,-67916740.0,192487245.0,183829287.0
16501,흥아해운(주),3280,2018/12,73148175.0,-86540156.0,56731554.0,-96953501.0,116884496.0,107614965.0
16502,흥아해운(주),3280,2019/12,30919383.0,-51356551.0,17632229.0,-52550693.0,73148175.0,56731554.0

In [ ]:
for i in range(0, len(df_rate_a)):
    if df_rate_a.iloc[i]["[제조]자본(*)(IFRS)"] < 0 and df_rate_a.iloc[i]["[제조]당기순이익(손실)(IFRS)"] < 0 :
        df_rate_a.loc[i, "자기자본순이익률(개별)"] = 11111111.11
    else:
        df_rate_a.loc[i, "자기자본순이익률(개별)"] = df_rate_a.iloc[i]["[제조]당기순이익(손실)(IFRS)"]/((df_rate_a.iloc[i]["[제조]자본(*)(IFRS)"] + df_rate_a.iloc[i]["[제조]자본(*)(IFRS2)"])/2)
    
    if df_rate_a.iloc[i]["[제조]자본(*)(IFRS연결)"] < 0 and df_rate_a.iloc[i]["[제조]당기순이익(손실)(IFRS연결)"] < 0 :
        df_rate_a.loc[i, "자기자본순이익률(연결)"] = 11111111.11
    else:
        df_rate_a.loc[i, "자기자본순이익률(연결)"] = df_rate_a.iloc[i]["[제조]당기순이익(손실)(IFRS연결)"]/((df_rate_a.iloc[i]["[제조]자본(*)(IFRS연결)"] + df_rate_a.iloc[i]["[제조]자본(*)(IFRS연결2)"])/2)

In [ ]:
#df_rate_a.to_csv("../csv_data/자기자본테스트2.csv", encoding="CP949")

kill_2010 = df_rate_a[df_rate_a['회계년도'].str.contains("2010")].index
kill_2010

Int64Index([    0,    10,    20,    30,    40,    50,    60,    70,    80,
               90,
            ...
            16378, 16388, 16398, 16408, 16418, 16428, 16438, 16462, 16483,
            16493],
           dtype='int64', length=1353)

In [ ]:
df_rate_a_complete = df_rate_a.drop(kill_2010)
df_rate_a_complete

,회사명,거래소코드,회계년도,[제조]자본(*)(IFRS연결),[제조]당기순이익(손실)(IFRS연결),[제조]자본(*)(IFRS),[제조]당기순이익(손실)(IFRS),[제조]자본(*)(IFRS연결2),[제조]자본(*)(IFRS2),자기자본순이익률(개별),자기자본순이익률(연결)
1,(주)CMG제약,58820,2011/12,18034249.0,-1508282.0,18290915.0,-1264488.0,18405116.0,18405116.0,-0.068917,-0.082783
2,(주)CMG제약,58820,2012/12,31590685.0,-6660149.0,31602540.0,-6892739.0,18034249.0,18290915.0,-0.276298,-0.268419
3,(주)CMG제약,58820,2013/12,48997281.0,296181.0,49048213.0,335258.0,31590685.0,31602540.0,0.008314,0.007351
4,(주)CMG제약,58820,2014/12,49002644.0,158039.0,49067039.0,171502.0,48997281.0,49048213.0,0.003496,0.003225
5,(주)CMG제약,58820,2015/12,46806888.0,-3650091.0,46872705.0,-3648668.0,49002644.0,49067039.0,-0.076062,-0.076195
...,...,...,...,...,...,...,...,...,...,...,...
16498,흥아해운(주),3280,2015/12,173076634.0,10517216.0,161824549.0,8827312.0,167402807.0,153935831.0,0.055911,0.061779
16499,흥아해운(주),3280,2016/12,192487245.0,-17173253.0,183829287.0,-16149442.0,173076634.0,161824549.0,-0.093443,-0.093955
16500,흥아해운(주),3280,2017/12,116884496.0,-73500411.0,107614965.0,-67916740.0,192487245.0,183829287.0,-0.466070,-0.475159
16501,흥아해운(주),3280,2018/12,73148175.0,-86540156.0,56731554.0,-96953501.0,116884496.0,107614965.0,-1.179867,-0.910792
16502,흥아해운(주),3280,2019/12,30919383.0,-51356551.0,17632229.0,-52550693.0,73148175.0,56731554.0,-1.413341,-0.986985

In [ ]:
df_rate_a_complete.to_csv("../csv_data/자기자본테스트3.csv", encoding="CP949")