In [30]:
import pandas as pd
import numpy as np

In [31]:
df_a = pd.read_csv("../csv_data/00_증가율1차.csv", thousands=',', encoding="CP949")
df_b = pd.read_csv("../csv_data/00_이자보상배율.csv", thousands=',', encoding="CP949")

In [32]:
df_a.drop(columns=['Unnamed: 0'], inplace=True)

In [33]:
df_b = df_b['이자보상배율']
df_b

0         3.53
1        -7.75
2         0.70
3         3.60
4       -32.22
         ...
15145     1.02
15146     0.21
15147    -0.42
15148    -1.16
15149     0.00
Name: 이자보상배율, Length: 15150, dtype: float64

In [34]:
df_c = pd.concat([df_a, df_b], axis=1)

In [35]:
df_c

,회사명,거래소코드,회계년도,총자본증가율,유형자산증가율,유동자산증가율,재고자산증가율,자기자본증가율,매출액증가율,정상영업이익증가율,...,순운전자본회전률,운전자본회전률,노동장비율,기계장비율,자본집약도,총자본투자효율,설비투자효율,기계투자효율,부가가치율,이자보상배율
0,(주)CMG제약,58820,2011,1.98,-5.90,17.64,-1.43,-2.02,56.40,0.00,...,0.86,0.00,71.32,19.75,204.06,12.72,35.86,1.285100e+02,19.56,3.53
1,(주)CMG제약,58820,2012,109.15,-4.12,207.08,7.73,75.17,-8.43,0.00,...,0.42,0.00,69.14,18.64,425.29,0.47,2.89,1.067000e+01,1.66,-7.75
2,(주)CMG제약,58820,2013,-2.09,16.09,-18.89,56.29,55.10,25.51,0.00,...,0.42,0.79,66.01,17.77,411.48,12.51,77.91,2.894000e+02,34.29,0.70
3,(주)CMG제약,58820,2014,3.86,74.30,-25.93,6.37,0.01,11.52,-46.64,...,0.56,0.74,113.90,32.60,354.43,12.16,37.80,1.320600e+02,31.04,3.60
4,(주)CMG제약,58820,2015,-2.64,-5.37,-7.17,11.04,-4.48,18.85,0.00,...,0.75,0.60,114.25,30.43,362.77,7.63,24.21,9.092000e+01,15.96,-32.22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15145,흥아해운(주),3280,2015,21.93,49.36,-11.18,-12.92,3.39,2.42,-42.68,...,2.15,0.01,589.65,0.00,948.60,13.11,21.49,3.459744e+09,12.28,1.02
15146,흥아해운(주),3280,2016,21.08,38.84,-25.08,56.39,11.22,-1.58,-263.29,...,2.19,0.02,703.55,0.00,1000.62,10.98,15.81,3.509713e+09,12.66,0.21
15147,흥아해운(주),3280,2017,-11.43,-16.50,13.29,11.18,-39.28,0.56,0.00,...,2.09,0.02,0.00,0.00,0.00,5.43,8.35,1.535742e+09,5.51,-0.42
15148,흥아해운(주),3280,2018,-5.33,-12.07,-6.33,-5.85,-37.42,-9.87,0.00,...,1.75,0.02,0.00,0.00,0.00,4.24,6.91,1.135163e+09,4.52,-1.16
15149,흥아해운(주),3280,2019,-46.38,-51.51,-13.42,-58.98,-57.73,-86.45,0.00,...,0.28,0.10,0.00,0.00,0.00,3.10,5.59,4.455416e+08,13.08,0.00

In [36]:
# 현재 데이터 기준으로 한계기업과 4년 연속 이.보.배 1 미만인 기업을 찾을 겁니다

f_company = [] # 한계기업을 저장하는 리스트
f_company_x = [] # 4년 연속 이자보상배율 1 미만인 기업 삽입
f_year = [] # 3년째 최초 연도
f_year_x = [] # 4년째 최초 연도
count = 0 # 한계기업 카운트용
company = 'x' # 한계기업 기록용

# 이거도 csv 한바퀴 돌립니다
for i in range(0, len(df_c)):

    # 회사명이 이미 기록된 상태에서 또 중복으로 적을 필요는 없습니다
    if company == df_c.iloc[i]['회사명']:
        # 다만 그 기업이 한계기업인데
        if count > 3:
            # 어머? 4년 연속이네요? 기록!!!
            if df_c.iloc[i]['이자보상배율'] < 1:
                f_company_x.append(company)
                f_year_x.append(df_c.iloc[i]['회계년도'])
                count = 0

                # 반복문에서 볼일 다 끝났으니 통과합니다
                continue
        
        # 그게 아니라면 반복문을 통과합니다
        continue

    # 이자보상배율이 1 미만인 경우 카운트를 늘립니다
    if df_c.iloc[i]['이자보상배율'] < 1:
            count += 1
    # 도중에 이자보상배율이 1 미만이면 탈출합니다
    else:
        count = 0

    # 한계 기업 클럽에 오셨습니다. 환영합니다.
    if count == 3:
        company = df_c.iloc[i]['회사명']
        f_company.append(company)
        f_year.append(df_c.iloc[i]['회계년도'])
        count += 1

In [37]:
fda = pd.DataFrame(f_year)
fdb = pd.DataFrame(f_year_x)
fdc = pd.DataFrame(f_company)
fdd = pd.DataFrame(f_company_x)
fde = pd.concat([fda, fdc, fdb, fdd], axis=1)
fde.to_csv("../csv_data/00_한계부실연도확인.csv", encoding="CP949")

In [38]:
# 분명히 이거보다 더 좋은 방법이 있을건데
# 맷돌이 굴러가질 않네요

# 이건 f_company 리스트에 들어잇는 데이터와 일치하면 True, 아니면 False를 반환합니다
df_limit = df_c.isin(f_company)
df_limit

,회사명,거래소코드,회계년도,총자본증가율,유형자산증가율,유동자산증가율,재고자산증가율,자기자본증가율,매출액증가율,정상영업이익증가율,...,순운전자본회전률,운전자본회전률,노동장비율,기계장비율,자본집약도,총자본투자효율,설비투자효율,기계투자효율,부가가치율,이자보상배율
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15145,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
15146,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
15147,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
15148,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
15149,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [39]:
df_limit_list = [] # 임시 저장용 리스트

# 그렇게 만든 데이터프레임을 기존과 비교해서 True인 애들만 뽑아옵니다
for i in range(0, len(df_c)):
    if df_limit.iloc[i]["회사명"] == True:
        df_limit_list.append(df_c.loc[i])

In [40]:
# 그리고 저장을 합니다
df_limit_df = pd.DataFrame(df_limit_list).reset_index(drop=True)
df_limit_df.to_csv("../csv_data/00_한계기업후보_v1.csv", encoding="CP949")

In [41]:
# 4년 연속 이자 보상 배율이 1 미만인 기업들도 똑같이 해봅니다

df_limitFour = df_c.isin(f_company_x)
df_limitFour_list = []

for i in range(0, len(df_c)):
    if df_limitFour.iloc[i]["회사명"] == True:
        df_limitFour_list.append(df_c.loc[i])

df_limitFour_df = pd.DataFrame(df_limitFour_list).reset_index(drop=True)
# 중간중간 저장은 선택이 아닌 필수
df_limitFour_df.to_csv("../csv_data/00_회생실패기업_v1.csv", encoding="CP949")

In [42]:
df_limit_df['회사명'].drop_duplicates()

0           (주)DB하이텍
9           (주)HJ중공업
18            (주)STX
27          (주)TCC스틸
36        (주)강스템바이오텍
            ...
4435    현대바이오사이언스(주)
4444         현우산업(주)
4453         휴림로봇(주)
4462         휴마시스(주)
4468         흥아해운(주)
Name: 회사명, Length: 535, dtype: object

In [43]:
df_limitFour_df['회사명'].drop_duplicates()

0           (주)DB하이텍
9           (주)HJ중공업
18            (주)STX
27        (주)강스템바이오텍
32          (주)강원에너지
            ...
3428         한일철강(주)
3437    현대바이오사이언스(주)
3446         휴림로봇(주)
3455         휴마시스(주)
3461         흥아해운(주)
Name: 회사명, Length: 407, dtype: object

In [46]:
df_test = df_limit_df.copy()
df_test

,회사명,거래소코드,회계년도,총자본증가율,유형자산증가율,유동자산증가율,재고자산증가율,자기자본증가율,매출액증가율,정상영업이익증가율,...,순운전자본회전률,운전자본회전률,노동장비율,기계장비율,자본집약도,총자본투자효율,설비투자효율,기계투자효율,부가가치율,이자보상배율
0,(주)DB하이텍,990,2011,-13.19,-7.89,-10.08,-3.28,-22.60,-10.94,0.00,...,0.72,0.00,284.94,107.56,461.22,18.17,29.75,7.890000e+01,39.45,-0.75
1,(주)DB하이텍,990,2012,-3.44,-9.69,10.52,2.79,-5.57,6.98,0.00,...,0.61,0.00,287.76,95.01,498.73,21.22,37.03,1.122200e+02,41.58,-0.31
2,(주)DB하이텍,990,2013,-8.58,-7.20,-27.88,-8.69,-29.61,-16.42,0.00,...,0.63,0.00,280.56,79.53,489.96,18.10,31.86,1.124500e+02,38.80,-0.16
3,(주)DB하이텍,990,2014,-6.95,-6.96,11.04,-4.42,-41.05,14.98,0.00,...,0.86,0.00,275.62,68.42,501.23,19.02,33.99,1.369700e+02,33.00,0.67
4,(주)DB하이텍,990,2015,-0.02,-9.91,36.42,20.64,110.48,17.42,0.00,...,1.11,0.00,244.25,83.69,501.83,39.21,78.88,2.302400e+02,57.93,2.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4472,흥아해운(주),3280,2015,21.93,49.36,-11.18,-12.92,3.39,2.42,-42.68,...,2.15,0.01,589.65,0.00,948.60,13.11,21.49,3.459744e+09,12.28,1.02
4473,흥아해운(주),3280,2016,21.08,38.84,-25.08,56.39,11.22,-1.58,-263.29,...,2.19,0.02,703.55,0.00,1000.62,10.98,15.81,3.509713e+09,12.66,0.21
4474,흥아해운(주),3280,2017,-11.43,-16.50,13.29,11.18,-39.28,0.56,0.00,...,2.09,0.02,0.00,0.00,0.00,5.43,8.35,1.535742e+09,5.51,-0.42
4475,흥아해운(주),3280,2018,-5.33,-12.07,-6.33,-5.85,-37.42,-9.87,0.00,...,1.75,0.02,0.00,0.00,0.00,4.24,6.91,1.135163e+09,4.52,-1.16
4476,흥아해운(주),3280,2019,-46.38,-51.51,-13.42,-58.98,-57.73,-86.45,0.00,...,0.28,0.10,0.00,0.00,0.00,3.10,5.59,4.455416e+08,13.08,0.00

In [50]:
company_index = []

for i in range(0,len(df_test)):
    # 컬럼들 순회합니다
    for j in range(0, len(df_test.columns)-3):
        # 회사명이 이미 기록된 상태에서 또 중복으로 적을 필요는 없습니다
        if company == df_c.iloc[i]['회사명']:
            # 다만 그 기업이 한계기업인데
            if count > 3:
                # 어머? 4년 연속이네요? 기록!!!
                if df_c.iloc[i]['이자보상배율'] < 1:
                    f_company_x.append(company)
                    f_year_x.append(df_c.iloc[i]['회계년도'])
                    count = 0

                    # 반복문에서 볼일 다 끝났으니 통과합니다
                    continue
            
            # 그게 아니라면 반복문을 통과합니다
            continue

        # 이자보상배율이 1 미만인 경우 카운트를 늘립니다
        if df_c.iloc[i]['이자보상배율'] < 1:
                count += 1
        # 도중에 이자보상배율이 1 미만이면 탈출합니다
        else:
            count = 0

        # 한계 기업 클럽에 오셨습니다. 환영합니다.
        if count == 3:
            company = df_c.iloc[i]['회사명']
            f_company.append(company)
            f_year.append(df_c.iloc[i]['회계년도'])
            count += 1

Index(['회사명', '거래소코드', '회계년도', '총자본증가율', '유형자산증가율', '유동자산증가율', '재고자산증가율',
       '자기자본증가율', '매출액증가율', '정상영업이익증가율', '순이익증가율', '매출액총이익률', '매출액순이익률',
       '총자본순이익률', '자기자본순이익률', '매출원가 대 매출액비율', '금융비용부담률', '금융비용 대 총비용비율',
       '이자부담률', '지급이자율', '차입금평균이자율', '매출액정상영업이익률', '유동자산구성비율', '재고자산 대 유동자산비율',
       '당좌자산구성비율', '자기자본구성비율', '타인자본구성비율', '자기자본배율', '유동비율', '당좌비율', '현금비율',
       '재고자산 대 순운전자본비율', '매출채권 대 매입채무비율', '부채비율', '유동부채비율', '단기차입금 대 총차입금비율',
       '순운전자본비율', '차입금비율', 'CASH FLOW 대 부채비율', 'CASH FLOW 대 차입금비율',
       'CASH FLOW 대 매출액비율', '총자본회전률', '자기자본회전률', '타인자본회전률', '매입채무회전률',
       '유동자산회전률', '당좌자산회전률', '재고자산회전률', '매출채권회전률', '유형자산회전율', '순운전자본회전률',
       '운전자본회전률', '노동장비율', '기계장비율', '자본집약도', '총자본투자효율', '설비투자효율', '기계투자효율',
       '부가가치율', '이자보상배율'],
      dtype='object')

In [141]:
list_test = [-1.16,1,2,3,4,5]

index_test = df_test[df_test['이자보상배율'].isin(list_test)].index
index_test

Int64Index([ 377,  750, 1405, 1639, 1730, 2514, 2542, 2650, 2667, 2718, 4382,
            4384, 4423, 4475],
           dtype='int64')

In [ ]:
# 상장폐지 코드 인덱스에 해당하는 컬럼이 있다면 회사명처럼 따로 아예 뽑아서 만들어도 되겠는데...?
# df_5_frame['부실기업'] = 0
# df_9 = df_5_frame.isin(df_7_frame)
# for i in range(0, len(df_5_frame)):
#     if df_9.iloc[i]['회사명'] == True:
#         df_5_frame.loc[i, '부실기업'] = 1
# df_5_frame