In [27]:
import pandas as pd
import numpy as np

In [28]:
# 경고가 많아지면 곤란해서(? 짜증나서) 추가
import warnings
warnings.filterwarnings('ignore')

In [29]:
df = pd.read_csv("../../csv_data/use/dataset3_2.csv", thousands=",", encoding="UTF-8")
#df.drop(columns=["Unnamed: 0"], inplace=True)

In [30]:
df

,회사명,거래소코드,회계년도,이자보상배율,총자산증가율,유형자산증가율,유동자산증가율,자기자본증가율,매출액증가율,매출액총이익율,매출액순이익율,자기자본순이익율,총자본영업이익율,매출액영업이익률,총자본순이익률,총자본회전율,재고자산회전율,매출채권회전율,유형자산회전율,매입채무회전율,자기자본회전율,타인자본회전율,유동자산회전율,순운전자본회전율,유동비율,당좌비율,현금비율,부채비율,차입금의존도,CASH_FLOW_대_부채비율,CASH_FLOW_대_매출액비율,CASH_FLOW_대_차입금비율,자기자본구성비율,당좌자산구성비율,유동자산구성비율,매출채권_대_매입채무비율,유동부채비율,타인자본구성비율,재고자산_대_유동자산비율,재고자산_대_순운전자본비율,순운전자본비율,노동장비율,기계장비율,자본집약도,설비투자효율,총자본투자효율,부가가치율,종업원1인당부가가치,R & D 투자효율,매출원가감소율여부,배당금감소율여부,변화율여부,직원감소율여부,자본증가율여부,투자활동감소율여부,기업수명주기,통계청 한국표준산업분류 10차(세세분류),회생기업1,회생기업2
0,(주)케이이씨,92220,201112,-1.92,-3.97,-9.01,3.09,-14.14,-11.92,4.86,-13.34,-22.34,-5.42,-8.79,-8.23,0.62,3.56,3.46,1.07,8.31,1.67,0.98,1.50,-10.06,77.25,44.95,9.65,187.71,45.91,0.31,0.32,0.43,34.76,24.74,42.52,251.16,158.37,65.24,41.81,-141.95,-12.52,327117.43,129560.18,619.70,27.172023,14.34,22.76,88884.42,2.67,0,0,0,0,0,0,1,"다이오드, 트랜지스터 및 유사 반도체소자 제조업",0,0
1,(주)케이이씨,92220,201212,-1.64,-14.54,-10.89,-23.08,-7.13,-13.10,3.97,-20.08,-32.80,-5.15,-8.73,-11.86,0.59,3.51,3.33,1.03,9.23,1.63,0.92,1.46,-12.32,78.63,49.31,10.10,164.76,35.76,0.34,0.33,0.60,37.77,24.00,38.27,286.89,128.87,62.23,37.28,-137.17,-10.40,331720.40,127439.93,570.15,15.750528,9.16,14.30,52247.72,2.70,0,0,0,0,0,0,4,"다이오드, 트랜지스터 및 유사 반도체소자 제조업",0,0
2,(주)케이이씨,92220,201312,-0.66,-8.11,-16.56,4.56,0.81,-0.94,12.26,-10.79,-18.06,-1.90,-2.88,-7.14,0.66,4.16,3.38,1.18,10.13,1.67,1.09,1.62,646.03,100.49,69.11,8.73,141.33,37.64,5.04,4.28,7.85,41.44,29.95,43.55,297.40,104.58,58.56,31.23,6361.68,0.21,295230.56,102206.88,555.67,36.087416,19.17,27.76,106541.08,2.52,0,0,0,0,0,0,3,"다이오드, 트랜지스터 및 유사 반도체소자 제조업",0,0
3,(주)케이이씨,92220,201412,0.42,-7.86,-9.94,-6.28,-2.89,-15.34,15.56,1.47,2.11,0.86,1.41,0.90,0.61,3.46,2.65,1.16,8.31,1.43,1.06,1.39,-18.21,86.41,54.76,4.50,128.99,35.46,0.98,0.87,1.55,43.67,28.07,44.30,278.59,117.39,56.33,36.62,-232.85,-6.97,270973.77,78679.85,521.24,44.140642,22.95,36.17,119609.56,1.99,0,0,0,0,0,0,5,"다이오드, 트랜지스터 및 유사 반도체소자 제조업",0,0
4,(주)케이이씨,92220,201512,0.90,-1.78,-7.11,3.79,-0.25,-4.93,16.41,0.25,0.35,1.41,2.32,0.15,0.61,3.10,2.31,1.20,9.20,1.38,1.09,1.34,13.28,124.64,80.47,5.07,125.49,28.32,0.56,0.51,1.10,44.35,30.22,46.81,462.41,84.68,55.65,35.43,179.26,9.25,261076.22,58966.18,543.00,43.807204,21.06,34.29,114370.19,2.01,0,0,0,0,0,0,2,"다이오드, 트랜지스터 및 유사 반도체소자 제조업",0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2656,한양디지텍(주),78350,201512,28.70,-7.63,16.37,-23.50,10.62,35.10,12.33,3.45,10.05,8.65,5.40,5.53,1.60,11.70,10.10,5.50,6.82,2.91,3.56,3.66,40.16,126.63,81.00,39.29,66.19,9.53,19.85,4.74,82.97,60.17,25.25,39.47,48.40,51.80,39.83,36.03,171.33,8.30,575587.81,618636.00,1772.84,79.347762,25.76,15.45,456716.05,0.22,0,0,0,0,0,1,성숙기,전자집적회로 제조업,0,0
2657,한양디지텍(주),78350,201612,2.39,-13.50,-0.57,-30.60,-4.97,-30.62,9.51,-0.79,-1.55,0.70,0.57,-0.97,1.24,8.89,10.06,3.56,6.32,1.97,3.35,3.46,55.93,117.78,77.72,28.41,51.26,9.52,8.90,2.26,31.69,66.11,20.90,31.67,69.24,40.67,33.89,34.02,225.29,4.78,587079.33,603496.07,1570.00,45.327045,16.95,12.68,266105.71,0.41,0,0,0,0,0,0,성숙기,전자집적회로 제조업,0,0
2658,한양디지텍(주),78350,201712,-14.80,-10.68,-6.26,-27.37,-9.07,-13.03,8.57,-2.84,-5.23,-4.29,-3.49,-3.48,1.23,15.47,9.77,3.20,7.52,1.84,3.69,4.25,-250.53,96.12,83.68,32.60,48.59,6.35,16.73,4.20,86.22,67.30,22.42,25.75,79.24,39.81,32.70,12.94,-320.54,-1.04,503410.37,506486.83,1280.44,36.454095,14.33,11.01,183513.70,0.61,0,0,0,0,0,0,성숙기,전자집적회로 제조업,0,0
2659,한양디지텍(주),78350,201812,13.70,11.66,-6.55,36.55,2.46,22.54,12.69,1.00,2.34,4.71,3.13,1.50,1.51,20.86,11.32,4.19,7.55,2.34,4.23,5.24,149.97,106.44,76.10,27.79,61.95,5.60,24.22,6.48,165.53,61.75,22.51,31.49,53.88,47.91,38.25,28.50,470.99,1.91,450943.02,498107.71,1370.23,0.000000,20.39,14.27,279433.75,1.01,0,0,0,0,0,1,성숙기,전자집적회로 제조업,0,0
2660,한양디지텍(주),78350,201912,-3.94,43.17,101.77,39.10,-28.83,-27.67,5.15,-18.81,-36.77,-9.93,-11.68,-15.98,0.85,10.51,8.39,2.08,4.99,1.96,1.50,2.75,-7.68,61.93,48.25,26.87,225.79,16.99,-2.65,-2.55,-10.82,30.69,23.83,30.59,60.24,160.94,69.31,22.09,-35.93,-18.81,924346.64,496554.64,2003.55,-0.919039,-0.42,-0.59,-8495.11,1.45,0,0,0,0,0,1,도입기,전자집적회로 제조업,0,0

In [31]:
df2 = df[["회사명", "거래소코드", "회계년도", "이자보상배율"]]

In [32]:
df2

           회사명  거래소코드    회계년도  이자보상배율
0      (주)케이이씨  92220  201112   -1.92
1      (주)케이이씨  92220  201212   -1.64
2      (주)케이이씨  92220  201312   -0.66
3      (주)케이이씨  92220  201412    0.42
4      (주)케이이씨  92220  201512    0.90
...        ...    ...     ...     ...
2656  한양디지텍(주)  78350  201512   28.70
2657  한양디지텍(주)  78350  201612    2.39
2658  한양디지텍(주)  78350  201712  -14.80
2659  한양디지텍(주)  78350  201812   13.70
2660  한양디지텍(주)  78350  201912   -3.94

[2661 rows x 4 columns]

In [33]:
# 다음 연도의 이자보상배율을 저장
df2['이보배2'] = df2['이자보상배율'].shift(-1).where(df2['회사명']==(df2['회사명']).shift(-1))
df2

           회사명  거래소코드    회계년도  이자보상배율   이보배2
0      (주)케이이씨  92220  201112   -1.92  -1.64
1      (주)케이이씨  92220  201212   -1.64  -0.66
2      (주)케이이씨  92220  201312   -0.66   0.42
3      (주)케이이씨  92220  201412    0.42   0.90
4      (주)케이이씨  92220  201512    0.90   0.76
...        ...    ...     ...     ...    ...
2656  한양디지텍(주)  78350  201512   28.70   2.39
2657  한양디지텍(주)  78350  201612    2.39 -14.80
2658  한양디지텍(주)  78350  201712  -14.80  13.70
2659  한양디지텍(주)  78350  201812   13.70  -3.94
2660  한양디지텍(주)  78350  201912   -3.94    NaN

[2661 rows x 5 columns]

In [34]:
# 부실징후기업의 경우 1, 아닌 경우 0을 기록

for i in range(0, len(df)):
    if df.iloc[i]['이자보상배율'] < 1:
        df2.loc[i, '부실기업'] = 1
    else:
        df2.loc[i, '부실기업'] = 0

In [35]:
df2['부실기업'] = df2['부실기업'].fillna(0)

In [36]:
df2

           회사명  거래소코드    회계년도  이자보상배율   이보배2  부실기업
0      (주)케이이씨  92220  201112   -1.92  -1.64   1.0
1      (주)케이이씨  92220  201212   -1.64  -0.66   1.0
2      (주)케이이씨  92220  201312   -0.66   0.42   1.0
3      (주)케이이씨  92220  201412    0.42   0.90   1.0
4      (주)케이이씨  92220  201512    0.90   0.76   1.0
...        ...    ...     ...     ...    ...   ...
2656  한양디지텍(주)  78350  201512   28.70   2.39   0.0
2657  한양디지텍(주)  78350  201612    2.39 -14.80   0.0
2658  한양디지텍(주)  78350  201712  -14.80  13.70   1.0
2659  한양디지텍(주)  78350  201812   13.70  -3.94   0.0
2660  한양디지텍(주)  78350  201912   -3.94    NaN   1.0

[2661 rows x 6 columns]

In [37]:
#df2['회생기업1'] = 0
#df2['회생기업2'] = 0

In [38]:
# t+1 이상의 기업들 중 살아난 기업 찾기
t_one = []
count = 0
#count_for_f = 0
company = df2.iloc[0]['회사명']

for i in range(0, len(df2)):

    if company != df2.iloc[i]['회사명']:
        company = df2.iloc[i]['회사명']
        count = 0
        #count_for_f = 0
        #continue #is it?

    elif count > 0:
        continue

    if df2.iloc[i]['이자보상배율'] < 1 and df2.iloc[i]['이보배2'] >= 1 and df2.iloc[i]['부실기업']== 1:
        df2.loc[i, '회생기업1'] = 1
        count += 1

In [39]:
df2

           회사명  거래소코드    회계년도  이자보상배율   이보배2  부실기업  회생기업1
0      (주)케이이씨  92220  201112   -1.92  -1.64   1.0    NaN
1      (주)케이이씨  92220  201212   -1.64  -0.66   1.0    NaN
2      (주)케이이씨  92220  201312   -0.66   0.42   1.0    NaN
3      (주)케이이씨  92220  201412    0.42   0.90   1.0    NaN
4      (주)케이이씨  92220  201512    0.90   0.76   1.0    NaN
...        ...    ...     ...     ...    ...   ...    ...
2656  한양디지텍(주)  78350  201512   28.70   2.39   0.0    NaN
2657  한양디지텍(주)  78350  201612    2.39 -14.80   0.0    NaN
2658  한양디지텍(주)  78350  201712  -14.80  13.70   1.0    NaN
2659  한양디지텍(주)  78350  201812   13.70  -3.94   0.0    NaN
2660  한양디지텍(주)  78350  201912   -3.94    NaN   1.0    NaN

[2661 rows x 7 columns]

In [40]:
# t+2 이상의 기업들 중 살아난 기업 찾기

t_two = []
count = 0
company = df2.iloc[0]['회사명']

for i in range(0, len(df2)):

    if company != df2.iloc[i]['회사명']:
        company = df2.iloc[i]['회사명']
        count = 0
        #continue #is it?

    if df2.iloc[i]['회생기업1'] == 1:
        count += 1
        #t_two.append(df2.loc[i])
        continue

    # elif count == 1:
    #     if df2.iloc[i]['부실기업'] == 0:
    #         #t_two.append(df2.loc[i])
    #         count = 0

    # elif df2.iloc[i]['부실기업'] == 1:
    #     continue

    elif count >= 1:
        # 부실기업이 아니고 이자보상배율과 그 다음해 이자보상배율(이보배2)가 모두 1 이상으로 건실하다고 판단된 경우
        if df2.iloc[i]['부실기업'] == 0 and df2.iloc[i]['이자보상배율'] >= 1 and df2.iloc[i]['이보배2'] >= 1:
            #if df2.iloc[i]['이자보상배율'] < 1 and df2.iloc[i]['이보배2'] >= 1:
                df2.loc[i, "회생기업2"] = 1
        count += 1
        #t_two.append(df2.loc[i])
        #continue

In [41]:
# # t+2 이상의 기업들 중 살아난 기업 찾기 (구)
# # 숫자 2 이상으로 조절해서 나가시면 됩니다
# # 밑에 파일명 바꾸는 거 조심하시구요

# t_two = []
# count = 0
# company = df2.iloc[0]['회사명']

# for i in range(0, len(df2)):

#     if company != df2.iloc[i]['회사명']:
#         company = df2.iloc[i]['회사명']
#         count = 0
#         continue #is it?

#     if df2.iloc[i]['부실기업'] == 1:
#         count += 1
#         #t_two.append(df2.loc[i])
#         continue

#     elif count == 1:
#         if df2.iloc[i]['부실기업'] == 0:
#             #t_two.append(df2.loc[i])
#             count = 0

#     elif count == 2:
#         # 부실기업이 아니고 이자보상배율과 그 다음해 이자보상배율(이보배2)가 모두 1 이상으로 건실하다고 판단된 경우
#         if df2.iloc[i]['부실기업'] == 0 and df2.iloc[i]['이자보상배율'] >= 1 and df2.iloc[i]['이보배2'] >= 1:
#             #if df2.iloc[i]['이자보상배율'] < 1 and df2.iloc[i]['이보배2'] >= 1:
#                 df2.loc[i, "회생기업2"] = 1
#         count += 1
#         #t_two.append(df2.loc[i])
#         continue

#     else:
#         t_two.append(df2.loc[i])

In [42]:
df2['회생기업1'] = df2['회생기업1'].shift().where(df2['회사명']==(df2['회사명']).shift())
df2['회생기업2'] = df2['회생기업2'].shift().where(df2['회사명']==(df2['회사명']).shift())

In [43]:
df2.tail(10)

            회사명  거래소코드    회계년도  이자보상배율   이보배2  부실기업  회생기업1  회생기업2
2651  하나마이크론(주)  67310  201912    3.01    NaN   0.0    NaN    1.0
2652   한양디지텍(주)  78350  201112    0.03  -2.62   1.0    NaN    NaN
2653   한양디지텍(주)  78350  201212   -2.62   6.36   1.0    NaN    NaN
2654   한양디지텍(주)  78350  201312    6.36  25.92   0.0    1.0    NaN
2655   한양디지텍(주)  78350  201412   25.92  28.70   0.0    NaN    1.0
2656   한양디지텍(주)  78350  201512   28.70   2.39   0.0    NaN    1.0
2657   한양디지텍(주)  78350  201612    2.39 -14.80   0.0    NaN    1.0
2658   한양디지텍(주)  78350  201712  -14.80  13.70   1.0    NaN    NaN
2659   한양디지텍(주)  78350  201812   13.70  -3.94   0.0    NaN    NaN
2660   한양디지텍(주)  78350  201912   -3.94    NaN   1.0    NaN    NaN

In [44]:
df2.to_csv("t회생시험7.csv", encoding="CP949")

In [45]:
# pd.DataFrame(t_one).to_csv("t_1.csv", encoding="CP949")

In [46]:
# pd.DataFrame(t_two).to_csv("t_2.csv", encoding="CP949")

In [47]:
df3 = df2.copy()
df3['회생기업1'] = df3['회생기업1'].fillna(0)
df3['회생기업2'] = df3['회생기업2'].fillna(0)

In [48]:
df3['회생기업1'].value_counts()

0.0    2426
1.0     235
Name: 회생기업1, dtype: int64

In [49]:
df3['회생기업2'].value_counts()

0.0    2221
1.0     440
Name: 회생기업2, dtype: int64

In [50]:
#pd.options.display.max_columns = None

#pd.DataFrame(df3['회사명'].value_counts()).to_csv("testt.csv", encoding="CP949")